// packages/solid/src/lib/with-kairo.ts
import {
  Component,
  onCleanup,
  getListener,
  useContext,
  createSignal,
  runWithOwner,
  getOwner,
  onMount,
  untrack,
  PropsWithChildren,
} from 'solid-js';
import { Cell, collectScope, Reaction } from 'kairo';
import type { JSX } from 'solid-js';
import { KairoContext } from './context';

function patchedTrack<T>(
  cell: Cell<T> & {
    signal_ref?: WeakMap<ReturnType<typeof getOwner>, Function>;
  }
) {
  if (getListener()) {
    const { owner } = getListener();
    if (!cell.signal_ref) {
      cell.signal_ref = new WeakMap();
    }
    const refRead = cell.signal_ref.get(owner);
    if (refRead === undefined) {
      const update = () => {
        reaction.track(($) => write(() => untrack(() => $(cell))));
      };
      const reaction = new Reaction(update);
      const [read, write] = createSignal();
      update();
      cell.signal_ref.set(owner, read);
      runWithOwner(owner, () => {
        onCleanup(() => {
          reaction.dispose();
          cell.signal_ref.delete(owner);
        });
      });
      return read();
    } else {
      return refRead();
    }
  }
  return Cell.track(cell);
}

function withKairo<Props>(
  setup: (
    props: Props
  ) => (
    track: typeof Cell.track,
    props: PropsWithChildren<Props>
  ) => JSX.Element
): Component<Props> {
  return (
    props: Props & {
      children?: JSX.Element;
    }
  ) => {
    const context = useContext(KairoContext);

    const exitScope = collectScope();
    const exitContext = context.runInContext();
    let Component: (
      track: typeof Cell.track,
      props: PropsWithChildren<Props>
    ) => JSX.Element;
    try {
      Component = setup({
        ...props,
      } as any);
    } finally {
      exitContext();
      const lifecycle = exitScope();
      onMount(() => {
        const dispose = lifecycle.attach();
        onCleanup(dispose);
      });
    }

    return Component(patchedTrack, props);
  };
}

export { withKairo };

// libs/react-lib/src/lib/with-kairo.ts
import {
  lifecycle,
  Reaction,
  collectScope,
  LifecycleScope,
} from 'kairo';
import React, {
  useContext,
  useEffect,
  useMemo,
  forwardRef as reactForwardRef,
  useState,
  useRef,
} from 'react';
import { KairoContext } from './context';

type FunctionComponent<T> = React.FunctionComponent<T>;
type ForwardRefRenderFunction<R, T> = React.ForwardRefRenderFunction<R, T>;

export function withKairo<Props>(
  setup: (props: Props) => FunctionComponent<Props>
) {
  const component: FunctionComponent<Props> = (props) => {
    const { renderFunction, renderReaction } = useKairoComponent(props, setup);

    return renderReaction.track(() => renderFunction(props));
  };
  component.displayName = setup.name;
  return component;
}

export function forwardRef<Props, Ref>(
  setup: (props: Props) => ForwardRefRenderFunction<Ref, Props>
) {
  const component: ForwardRefRenderFunction<Ref, Props> = (props, ref) => {
    const { renderFunction, renderReaction } = useKairoComponent(props, setup);

    return renderReaction.track(() => renderFunction(props, ref));
  };
  component.displayName = setup.name;
  return reactForwardRef(component);
}

const inc = (x: number) => x + 1;

function useKairoComponent<Props>(
  props: Props,
  setup: (props: Props) => FunctionComponent<Props>
) {
  const parentContext = useContext(KairoContext);
  const [, forceUpdate] = useState(0);
  const instance = useMemo(() => {
    const exitScope = collectScope();
    const exitContext = parentContext.runInContext();
    let renderFunction: FunctionComponent<Props>;
    let scope: LifecycleScope;
    let didMounted = false,
      didUpdateBeforeMounted = false;
    lifecycle(() => {
      didMounted = true;
      if (didUpdateBeforeMounted) {
        forceUpdate(inc); // schedule an update
        didUpdateBeforeMounted = false;
      }
      return () => {
        didMounted = false;
        renderReaction.dispose();
      };
    });
    try {
      renderFunction = setup(props);
    } finally {
      exitContext();
      scope = exitScope();
    }
    const renderReaction = new Reaction(() => {
      if (!didMounted) {
        renderReaction.dispose();
        didUpdateBeforeMounted = true;
        // if it's the first render of strict mode,
      } else {
        forceUpdate(inc);
      }
    });

    return {
      renderFunction,
      renderReaction,
      scope,
    };
  }, []);
  useEffect(() => instance.scope.attach(), []);
  return instance;
}
