// libs/react-lib/src/lib/application.ts
import { collectScope, Concern } from 'kairo';
import { KairoContext } from './context';
import React, { useContext, useEffect, useMemo } from 'react';

export function withConcern<P>(
  concern: Concern,
  Component: React.ComponentType<P>
) {
  const Module: React.FunctionComponent<P> = (props) => {
    const parentContext = useContext(KairoContext);
    const [context, scope] = useMemo(() => {
      const exitScope = collectScope();
      return [parentContext.build(concern), exitScope()];
    }, []);
    useEffect(() => {
      return scope.attach();
    }, []);
    return React.createElement(
      KairoContext.Provider,
      { value: context },
      React.createElement(Component, props)
    );
  };

  return Module;
}

// packages/solid/src/lib/application.ts
import { Concern, collectScope, CONCERN_HOC_FACTORY } from 'kairo';
import {
  Component,
  createComponent,
  onCleanup,
  onMount,
  useContext,
} from 'solid-js';
import { KairoContext } from './context';

export function withConcern(concern: Concern) {
  return <Props>(component: Component<Props>): Component<Props> => {
    return (props: Props) => {
      const currentContext = useContext(KairoContext);
      const exitScope = collectScope();
      try {
        const context = currentContext.inherit({
          [CONCERN_HOC_FACTORY]: withConcern
        }).build(concern);
        return createComponent(KairoContext.Provider, {
          value: context,
          get children() {
            return createComponent(component, props);
          },
        });
      } finally {
        const scope = exitScope();
        onMount(() => {
          onCleanup(scope.attach());
        });
      }
    };
  };
}
