// packages/react/src/lib/application.ts
import {
  collectScope,
  Concern,
  CONCERN_HOC_FACTORY,
  Context,
  LifecycleScope,
} from 'kairo';
import { KairoContext } from './context';
import React, { useContext, useEffect, useState } from 'react';

export function withConcern(concern: Concern) {
  return <Props>(Component: React.ComponentType<Props>) => {
    const KairoModule: React.FunctionComponent<Props> = (props) => {
      const parentContext = useContext(KairoContext);
      const [[context, scope]] = useState(() => {
        const exitScope = collectScope();
        try {
          return [
            parentContext
              .inherit({
                [CONCERN_HOC_FACTORY]: withConcern,
              })
              .build(concern),
            exitScope(),
          ] as [Context, LifecycleScope];
        } catch (e) /* istanbul ignore next: captured by react */ {
          exitScope();
          throw e;
        }
      });
      useEffect(() => scope.attach(), []);
      return React.createElement(
        KairoContext.Provider,
        { value: context },
        React.createElement(Component, props)
      );
    };
    KairoModule.displayName = `withConcern(${Component.name})`;

    return KairoModule as React.ComponentType<Props>;
  };
}

// packages/solid/src/lib/application.ts
import { Concern, collectScope, CONCERN_HOC_FACTORY } from 'kairo';
import {
  Component,
  createComponent,
  onCleanup,
  onMount,
  useContext,
} from 'solid-js';
import { KairoContext } from './context';

export function withConcern(concern: Concern) {
  return <Props>(component: Component<Props>): Component<Props> => {
    return (props: Props) => {
      const currentContext = useContext(KairoContext);
      const exitScope = collectScope();
      try {
        const context = currentContext.inherit({
          [CONCERN_HOC_FACTORY]: withConcern
        }).build(concern);
        return createComponent(KairoContext.Provider, {
          value: context,
          get children() {
            return createComponent(component, props);
          },
        });
      } finally {
        const scope = exitScope();
        onMount(() => {
          onCleanup(scope.attach());
        });
      }
    };
  };
}
