// packages/react/src/lib/with-kairo.ts
import { Reaction, collectScope, LifecycleScope, Cell, CONCERN_HOC_FACTORY } from 'kairo';
import type { Track } from 'kairo';
import React, {
  useContext,
  useEffect,
  forwardRef as reactForwardRef,
  useReducer,
  useState,
} from 'react';
import { KairoContext } from './context';
import { withConcern } from './application';

type Render<T> = (
  track: Track,
  props: React.PropsWithChildren<T>
) => React.ReactElement<any, any> | null;
type RenderWithRef<R, T> = (
  track: Track,
  props: React.PropsWithChildren<T>,
  ref: React.ForwardedRef<R>
) => React.ReactElement<any, any> | null;

export function withKairo<Props>(setup: (props: Props) => Render<Props>) {
  const KairoComponent: React.FunctionComponent<Props> = (props) => {
    const { renderFunction, renderReaction } = useKairoComponent(props, setup);

    return renderReaction.track(($) => renderFunction($, props));
  };
  KairoComponent.displayName = setup.name;
  return KairoComponent;
}

export function forwardRef<Props, Ref>(
  setup: (props: Props) => RenderWithRef<Ref, Props>
) {
  const KairForwardRef: React.ForwardRefRenderFunction<Ref, Props> = (
    props,
    ref
  ) => {
    const { renderFunction, renderReaction } = useKairoComponent(props, setup);

    return renderReaction.track(($) => renderFunction($, props, ref));
  };
  KairForwardRef.displayName = setup.name;
  return reactForwardRef(KairForwardRef);
}

const inc = (x: number) => x + 1;

function useKairoComponent<Props, Render>(
  props: Props,
  setup: (props: Props) => Render
) {
  const parentContext = useContext(KairoContext);
  const [, forceUpdate] = useReducer(inc, 0);
  const [instance] = useState(() => {
    const exitScope = collectScope();
    const exitContext = parentContext.inherit({
      [CONCERN_HOC_FACTORY]: withConcern
    }).runInContext();
    let renderFunction: Render;
    let scope: LifecycleScope;
    try {
      renderFunction = setup(props);
    } finally {
      exitContext();
      scope = exitScope();
    }
    const renderReaction = new RenderReaction(forceUpdate);

    return {
      renderFunction,
      renderReaction,
      scope,
    };
  });
  useEffect(() => instance.renderReaction.mount(), []);
  useEffect(() => instance.scope.attach(), []);
  return instance;
}

class RenderReaction {
  private mounted = false;
  private logs: [Cell<any>, any][] = [];
  private _reaction: Reaction;

  constructor(private callback: () => void) {
    this._reaction = new Reaction(callback);
  }

  track<T>(program: ($: Track) => T) {
    if (this.mounted) {
      return this._reaction.track(program);
    } else {
      this.logs = [];
      const track = (cell: Cell<any>) => {
        const ret = cell.current;
        this.logs.push([cell, ret]);
        return ret;
      };
      Object.defineProperty(track, 'error', {
        value: (cell: Cell<any>) => {
          try {
            cell.current;
            this.logs.push([cell, null]);
            return null;
          } catch (e) {
            this.logs.push([cell, e]);
            return e;
          }
        },
      });
      return program(track as any);
    }
  }

  mount() {
    this.mounted = true;
    let needToRerender = false;
    this._reaction.track(($) => {
      this.logs.forEach((x) => {
        const ret = $(x[0]);
        needToRerender ||= !Object.is(ret, x[1]);
        return ret;
      });
    });
    this.logs = [];
    if (needToRerender) this.callback();
    return () => {
      this.mounted = false;
      this._reaction.dispose();
    };
  }
}

// packages/solid/src/lib/with-kairo.ts
import {
  Component,
  onCleanup,
  getListener,
  useContext,
  createSignal,
  runWithOwner,
  getOwner,
  onMount,
  untrack,
  PropsWithChildren,
} from 'solid-js';
import { Cell, collectScope, CONCERN_HOC_FACTORY, Reaction } from 'kairo';
import type { Track } from 'kairo';
import type { JSX } from 'solid-js';
import { KairoContext } from './context';
import { withConcern } from './application';

// function patchedTrack<T>(
//   cell: Cell<T> & {
//     signal_ref?: WeakMap<ReturnType<typeof getOwner>, Function>;
//   }
// ) {
//   if (getListener()) {
//     const { owner } = getListener();
//     if (!cell.signal_ref) {
//       cell.signal_ref = new WeakMap();
//     }
//     const refRead = cell.signal_ref.get(owner);
//     if (refRead === undefined) {
//       const update = () => {
//         console.log('hey update!');
//         console.log(cell.current);
//         reaction.track(($) => {
//           console.log('you should update?');
//           console.log($(cell))
//           write(() => untrack(() => $(cell)));
//         });
//       };
//       const reaction = new Reaction(update);
//       const [read, write] = createSignal();
//       update();
//       cell.signal_ref.set(owner, read);
//       runWithOwner(owner, () => {
//         onCleanup(() => {
//           console.log('imfucked');
//           reaction.dispose();
//           cell.signal_ref.delete(owner);
//         });
//       });
//       return read();
//     } else {
//       return refRead();
//     }
//   }
//   return cell.current;
// }

// TODO: it might not work with transition? test it out
function passiveTrack<T>(cell: Cell<T>) {
  if (getListener()) {
    let disposed = false;
    const reaction = new Reaction(() => {
      write(() => cell.current);
      if (disposed) {
        reaction.dispose();
      }
    });
    const [read, write] = createSignal();
    onCleanup(() => {
      disposed = true;
    });
    read(); // trig track
    return reaction.track(($) => $(cell));
  }
  return cell.current;
}

function passiveTrackError<T>(cell: Cell<T>) {
  if (getListener()) {
    let disposed = false;
    const reaction = new Reaction(() => {
      write(() => {
        try {
          cell.current;
          return null;
        } catch (e) {
          return e;
        }
      });
      if (disposed) {
        reaction.dispose();
      }
    });
    const [read, write] = createSignal();
    onCleanup(() => {
      disposed = true;
    });
    read(); // trig track
    return reaction.track(($) => {
      try {
        $(cell);
        return null;
      } catch (e) {
        return e;
      }
    });
  }
  try {
    cell.current;
    return null;
  } catch (e) {
    return e;
  }
}

Object.defineProperty(passiveTrack,'error',{value: passiveTrackError});

function withKairo<Props>(
  setup: (
    props: Props
  ) => (track: Track, props: PropsWithChildren<Props>) => JSX.Element
): Component<Props> {
  return (
    props: Props & {
      children?: JSX.Element;
    }
  ) => {
    const context = useContext(KairoContext);

    const exitScope = collectScope();
    const exitContext = context.inherit({
      [CONCERN_HOC_FACTORY]: withConcern
    }).runInContext();
    let Component: (
      track: Track,
      props: PropsWithChildren<Props>
    ) => JSX.Element;
    try {
      Component = setup({
        ...props,
      } as any);
    } finally {
      exitContext();
      const lifecycle = exitScope();
      onMount(() => {
        const dispose = lifecycle.attach();
        onCleanup(dispose);
      });
    }

    return Component(passiveTrack as any, props);
  };
}

export { withKairo };
