// libs/react-lib/src/lib/application.tsx
import { Scope } from 'kairo';
import { KairoContext } from './context';
import React, { useEffect } from 'react';

export function createKairoApp(setup?: () => void) {
  const rootScope = new Scope();
  const endScope = rootScope.beginScope();
  // platform setup (tokens)
  setup?.();
  endScope();
  const topScope = new Scope(undefined, rootScope);
  const App: React.FunctionComponent = ({ children }) => {
    useEffect(() => {
      return rootScope.attach();
    }, []);
    return (
      <KairoContext.Provider value={topScope}>{children}</KairoContext.Provider>
    );
  };

  return {
    scope: rootScope,
    App,
  };
}

// libs/solid-lib/src/lib/application.ts
import { Scope } from 'kairo';
import { Component, createComponent, onCleanup, onMount } from 'solid-js';
import { KairoContext } from './context';

export function createKairoApp(setup?: () => void) {
  const rootScope = new Scope();
  const endScope = rootScope.beginScope();
  // platform setup (tokens)
  setup?.();
  endScope();
  const topScope = new Scope(undefined, rootScope);
  const App: Component = (props) => {
    onMount(() => {
      onCleanup(rootScope.attach());
    });
    return createComponent(KairoContext.Provider, {
      value: topScope,
      get children() {
        return props.children;
      },
    });
  };

  return {
    scope: rootScope,
    App,
  };
}
