// libs/preact-lib/src/lib/with-kairo.tsx
import { transaction, Cell, Scope, effect, lazy, mutValue } from 'kairo';
import { useContext, useEffect, useMemo, useState } from 'preact/hooks';
import type { FunctionComponent, RenderableProps } from 'preact';
import { h } from 'preact';
import { KairoContext } from './context';

export const KairoApp: FunctionComponent<{
  globalSetup?: () => void;
}> = (props) => {
  const kairoScope = useMemo(() => {
    const scope = new Scope();
    const endScope = scope.beginScope();

    let propsSetter = [];
    $$CURRENT_HOOKS = [];
    const renderFn = props.globalSetup?.();
    Object.freeze(propsSetter);
    const hooks = $$CURRENT_HOOKS;
    $$CURRENT_HOOKS = null;
    endScope();
    return {
      renderFn,
      hooks,
      scope,
    };
  }, []);
  const { hooks, scope } = kairoScope;

  for (const hook of hooks) {
    hook(props);
  }

  useEffect(() => {
    return scope.attach();
  }, []);

  return (
    <KairoContext.Provider value={scope}>
      {props.children}
    </KairoContext.Provider>
  );
};

export function __unstable__runHooks<Props = any>(fn: (prop: Props) => void) {
  if ($$CURRENT_HOOKS === null) {
    throw Error(
      'You should only call is function when component initializing.'
    );
  }
  $$CURRENT_HOOKS.push(fn);
}

let $$CURRENT_HOOKS: Function[] | null = null;

export function withKairo<Props>(
  setup: (
    props: Props,
    useProp: <P>(selector: (x: Props) => P) => Cell<P>
  ) => FunctionComponent<Props>
): FunctionComponent<Props> {
  return function KairoComponent(props: RenderableProps<Props>) {
    const parentScope = useContext(KairoContext);
    const [_, setTick] = useState(0);
    const kairoScope = useMemo(() => {
      const scope = new Scope(parentScope);
      const endScope = scope.beginScope();

      let tick = 0;
      const propsSetter = [];
      $$CURRENT_HOOKS = [];
      const renderFn = setup(props, (selector) => {
        const [beh, set] = mutValue(selector(props));
        propsSetter.push((p: Props) => set(selector(p)));
        return beh;
      });
      Object.freeze(propsSetter);
      $$CURRENT_HOOKS.push((currentProps: Props) => {
        // the length should be fixed
        if (propsSetter.length) {
          useEffect(() => {
            // a hook to detect props change
            transaction(() => {
              propsSetter.forEach((x) => x(currentProps));
            });
          });
        }
      });
      const renderComp = lazy<ReturnType<typeof renderFn>>();
      effect(() => {
        const stop = renderComp.watch(() => {
          setTick(++tick);
        });
        renderComp.execute(() => renderFn(props)); // start
        return () => {
          stop();
        };
      });

      const hooks = $$CURRENT_HOOKS;
      $$CURRENT_HOOKS = null;

      endScope();
      return {
        renderFn,
        hooks,
        renderComp,
        scope,
      };
    }, []);
    const { hooks, renderFn, renderComp, scope } = kairoScope;

    useEffect(() => {
      return scope.attach();
    }, []);

    for (const hook of hooks) {
      hook(props);
    }

    return (
      <KairoContext.Provider value={scope}>
        {renderComp.execute(() => renderFn(props))}
      </KairoContext.Provider>
    );
  };
}

// libs/solid-lib/src/lib/with-kairo.ts
import {
  Component,
  onCleanup,
  getListener,
  createComponent,
  useContext,
  createSignal,
  createComputed,
  runWithOwner,
  getOwner,
  createEffect,
} from 'solid-js';
import {
  Cell,
  ComputationalCell,
  mutable,
  Scope,
  __current_collecting,
} from 'kairo';
import type { JSX } from 'solid-js';
import { KairoContext } from './context';

/**
 * side effects
 * patches prototype of Behavior
 */
const originalGetter = Object.getOwnPropertyDescriptor(Cell.prototype, 'value')
  .get;

Object.defineProperty(Cell.prototype, 'value', {
  get(
    this: Cell<any> & {
      signal_ref?: WeakMap<ReturnType<typeof getOwner>, [Function, Function]>;
    }
  ) {
    if (__current_collecting()) {
      return originalGetter.call(this);
    }
    if (getListener()) {
      if (!this.signal_ref) {
        this.signal_ref = new WeakMap();
      }
      const ref = this.signal_ref.get(getListener().owner);
      if (ref === undefined) {
        const owner = getListener().owner;
        const disposeWatcher = this.watch((v) => {
          ref2[1](v);
        });
        const ref2 = createSignal(originalGetter.call(this));
        this.signal_ref.set(owner, ref2);
        runWithOwner(owner, () => {
          onCleanup(() => {
            disposeWatcher();
            this.signal_ref.delete(owner);
          });
        });
        return ref2[0]();
      } else {
        return ref[0]();
      }
    }
    return originalGetter.call(this);
  },
});

const originalComputationGetter = Object.getOwnPropertyDescriptor(
  ComputationalCell.prototype,
  'value'
).get;

Object.defineProperty(ComputationalCell.prototype, 'value', {
  get(
    this: Cell<any> & {
      signal_ref?: WeakMap<ReturnType<typeof getOwner>, [Function, Function]>;
    }
  ) {
    if (__current_collecting()) {
      return originalComputationGetter.call(this);
    }
    if (getListener()) {
      if (!this.signal_ref) {
        this.signal_ref = new WeakMap();
      }
      const ref = this.signal_ref.get(getListener().owner);
      if (ref === undefined) {
        const owner = getListener().owner;
        const disposeWatcher = this.watch((v) => {
          ref2[1](v);
        });
        const ref2 = createSignal(originalComputationGetter.call(this));
        this.signal_ref.set(owner, ref2);
        runWithOwner(owner, () => {
          onCleanup(() => {
            disposeWatcher();
            this.signal_ref.delete(owner);
          });
        });
        return ref2[0]();
      } else {
        return ref[0]();
      }
    }
    return originalComputationGetter.call(this);
  },
});

function KairoApp(props: { globalSetup?: () => void; children: JSX.Element }) {
  const scope = new Scope(null);
  {
    const endScope = scope.beginScope();
    props.globalSetup?.();
    endScope();
  }
  createEffect(() => {
    const dispose = scope.attach();
    onCleanup(dispose);
  });

  return createComponent(KairoContext.Provider, {
    value: scope,
    get children() {
      return props.children;
    },
  });
}

function withKairo<Props>(
  setup: (
    props: Props,
    useProp: <P>(selector: (x: Props) => P) => Cell<P>
  ) => Component<Props>
): Component<Props> {
  return (
    props: Props & {
      children?: JSX.Element;
    }
  ) => {
    const parent = useContext(KairoContext);

    const scope = new Scope(parent);

    const endScope = scope.beginScope();
    const Component = setup(
      {
        ...props,
      } as any,
      (thunk) => {
        const [prop, setProp] = mutable(thunk(props));
        createComputed(() => {
          setProp(thunk(props));
        });
        return prop;
      }
    );
    endScope();

    createEffect(() => {
      const dispose = scope.attach();
      onCleanup(dispose);
    });

    return createComponent(KairoContext.Provider, {
      value: scope,
      get children() {
        return createComponent(Component, props);
      },
    });
  };
}

export { KairoApp, withKairo };
